### ISSUE TITLE
Not compatible with Venice 0.6

### ISSUE THREAD

**Issue by Dev1an** [VeniceX/UDP#5]
When adding this Module in a Module that already uses Venice 0.6, I get the following error after running `swift build`:
```
error: The dependency graph could not be satisfied because an update to 'https://github.com/VeniceX/Venice.git' is required
```

**Comment by antonmes** [comment]
Both packages was updated and should be compatible now.

**Comment by Dev1an** [comment]
Dear Anton,

The email sent to info@devian.tk with subject
"Re: [VeniceX/UDP] Not compatible with Venice 0.6 (#5)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to info@devian.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
